name: SlimeLink
version: '2.0.0'
main: dev.danielmillar.slimelink.SlimeLink
api-version: '1.21'
authors: [ Daniel Millar ]
website: https://github.danielmillar.dev/
description: SlimeLink is an addon for Skript for interacting with ASP (AdvancedSlimePaper)

dependencies:
  server:
    Skript:
      load: BEFORE
      required: true