name: SlimeLink
version: '1.1.2'
main: dev.danielmillar.slimelink.SlimeLink
api-version: '1.21'
author: Daniel Millar
website: https://github.danielmillar.dev/
description: SlimeLink is an addon for Skript for interacting with ASP (AdvancedSlimePaper)
depend:
  - Skript
load: POSTWORLD